---
# tasks file for lbrole
#
- name: "install haproxy package"
  package:
    name: "haproxy"
    state: present

- name: "configure haproxy"
  template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"

- name: "start haproxy service"
  service:
    name: "haproxy"
    state: started
